name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest main branch changes
        run: |
          cd /home/matsci_yamz/code
          git fetch origin
          git pull origin main

      - name: Stop yamz service
        run: |
          service matsci_yamz stop

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Run DB Migrations
        run: |
          pnpm db:migrate

      - name: Build NextJS App
        run: |
          pnpm build

      - name: Start Service
        run: |
          service matsci_yamz start
