name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working_directory: /home/matsci_yamz/code

    steps:
      - name: Pull latest main branch changes
        run: |
          git fetch origin
          git pull origin main

      - name: Stop yamz service
        run: |
          sudo /usr/bin/systemctl stop matsci_yamz

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Run DB Migrations
        run: |
          pnpm db:migrate

      - name: Build NextJS App
        run: |
          pnpm build

      - name: Start Service
        run: |
          sudo /usr/bin/systemctl start matsci_yamz 
